// Card decks for the Spark Deck — the anti-writer's-block idea slot machine.

export const DECKS = {
  GENRE: [
    "dreamy synthwave", "dusty boom-bap", "gothic surf rock", "cosmic disco",
    "lo-fi bedroom pop", "spaghetti-western trap", "junglist drum & bass",
    "krautrock motorik", "bossa nova noir", "hyperpop meltdown",
    "doom-country ballad", "8-bit chiptune anthem", "afrobeat groove",
    "shoegaze wall of sound", "minimal techno", "sea-shanty punk",
    "gospel-soul slow burn", "psychedelic cumbia", "industrial lullaby",
    "bluegrass breakbeat",
  ],
  MOOD: [
    "triumphant but exhausted", "sneaky midnight mischief", "sun-drunk euphoria",
    "beautiful paranoia", "last day of summer", "revenge in slow motion",
    "homesick for a place that doesn't exist", "dancing at the end of the world",
    "cocky and bulletproof", "tender and unguarded", "static-charged anticipation",
    "grief wearing sunglasses", "first-snow hush", "caffeinated invincibility",
    "underwater calm", "neon loneliness",
  ],
  "LEAD INSTRUMENT": [
    "detuned tack piano", "talkbox lead", "baritone guitar", "glass marimba",
    "screaming analog synth", "muted trumpet", "12-string acoustic",
    "toy glockenspiel", "fretless bass solo", "theremin", "kalimba",
    "vocoder choir", "slide dobro", "arpeggiated Juno pads", "church organ",
    "sitar through a fuzz pedal",
  ],
  TEXTURE: [
    "vinyl crackle & tape hiss", "cavernous gated reverb", "clipped and crunchy",
    "wide and glossy", "one-mic-in-a-garage raw", "sidechained heartbeat pump",
    "underwater lo-pass haze", "brittle AM-radio", "orchestral and cinematic",
    "dry, close, and intimate", "granular stutter glitch", "smoky late-night club",
  ],
  VOICE: [
    "airy female vocal", "smoky female alto", "powerhouse soul diva",
    "breathy whisper-pop vocal", "gravelly male baritone", "smooth R&B tenor",
    "aching male falsetto", "country-twang duet", "robotic vocoder voice",
    "auto-tuned melodic rap", "fast confident rap flow", "dreamy layered choir",
    "raspy punk shout", "late-night jazz crooner", "operatic soprano",
    "spoken-word over singing",
  ],
  ERA: [
    "1967 psychedelia", "1979 disco floor", "1985 montage scene", "1994 golden-era hip-hop",
    "2003 garage-rock revival", "2011 blog-house", "3024 chrome cathedral",
    "prohibition speakeasy", "silent-film piano pit", "Y2K mall food court",
  ],
};

export const DARES = [
  "Write the second verse FIRST. The first verse doesn't exist yet.",
  "The chorus may only ask questions. No statements allowed.",
  "Ban the word 'love'. Say it five other ways instead.",
  "Write from the villain's point of view — and make us agree with them.",
  "Every line must contain a color.",
  "The whole song happens in 30 seconds of real time.",
  "Steal the rhythm of a nursery rhyme, then make it menacing.",
  "The bridge must be a voicemail somebody never sent.",
  "Rhyme nothing. Tension comes from the drums, not the rhymes.",
  "Write the song title last. Everything else first.",
  "Your narrator is lying to us. Let it show by verse three.",
  "One instrument must do something it was never designed to do.",
  "Verse one is a wide shot. Verse two is a close-up on one object.",
  "The hook is one word, repeated until it stops meaning anything.",
  "Write it as a duet between you and yourself ten years ago.",
  "The last line must be the first line, but it means the opposite now.",
  "No 'I' allowed. The song is about you, but you never appear.",
  "Set it in the last place anything interesting should happen (a DMV, a dentist's office...).",
  "Start on the beat 'and'. Never let the phrase land where they expect.",
  "The drop is silence. Earn it.",
];

export const SEEDS = [
  "I left the porch light on for a version of me that never came home.",
  "The city sleeps in gasoline and hums like it knows my name.",
  "You laughed like the rent was paid.",
  "Half of my heart still lives at your old address.",
  "Nobody dances like they're being watched anymore.",
  "I found your handwriting in a book I never lent you.",
  "The moon clocked out early tonight.",
  "We were fluent in a language made of almosts.",
  "Static on the radio sounds like applause if you're lonely enough.",
  "Every red light in this town knows my confession.",
  "I traded my thunder for a quieter kind of loud.",
  "The last bus home smells like other people's perfume.",
  "My shadow keeps better time than I do.",
  "Heaven's just a dive bar with better lighting.",
  "I've been rehearsing goodbyes in the mirror since June.",
  "The ocean returned everything except your name.",
];
